"""
This type stub file was generated by pyright.
"""

from .prop_widgets_abstract import BaseProperty

class _PropVector(BaseProperty):
    """
    Base widget for the PropVector widgets.
    """
    def __init__(self, parent=..., fields=...) -> None:
        ...
    
    def set_data_type(self, data_type): # -> None:
        ...
    
    def get_value(self): # -> list[Any] | None:
        ...
    
    def set_value(self, value=...): # -> None:
        ...
    


class PropVector2(_PropVector):
    """
    Displays a node property as a "Vector2" widget in the PropertiesBin
    widget.

    Useful for display X,Y data.
    """
    def __init__(self, parent=...) -> None:
        ...
    


class PropVector3(_PropVector):
    """
    Displays a node property as a "Vector3" widget in the PropertiesBin
    widget.

    Useful for displaying x,y,z data.
    """
    def __init__(self, parent=...) -> None:
        ...
    


class PropVector4(_PropVector):
    """
    Displays a node property as a "Vector4"  widget in the PropertiesBin
    widget.

    Useful for display r,g,b,a data.
    """
    def __init__(self, parent=...) -> None:
        ...
    


