"""
This type stub file was generated by pyright.
"""

from .prop_widgets_abstract import BaseProperty

class PropFilePath(BaseProperty):
    """
    Displays a node property as a "QFileDialog" open widget in the
    PropertiesBin.
    """
    def __init__(self, parent=...) -> None:
        ...
    
    def set_file_ext(self, ext=...): # -> None:
        ...
    
    def set_file_directory(self, directory): # -> None:
        ...
    
    def get_value(self): # -> str:
        ...
    
    def set_value(self, value): # -> None:
        ...
    


class PropFileSavePath(PropFilePath):
    """
    Displays a node property as a "QFileDialog" save widget in the
    PropertiesBin.
    """
    ...


