"""
This type stub file was generated by pyright.
"""

from .prop_widgets_abstract import BaseProperty

class PropColorPickerRGB(BaseProperty):
    """
    Color picker widget for a node property.
    """
    def __init__(self, parent=...) -> None:
        ...
    
    def get_value(self): # -> tuple[Literal[0], Literal[0], Literal[0]] | tuple[Any, ...]:
        ...
    
    def set_value(self, value): # -> None:
        ...
    


class PropColorPickerRGBA(PropColorPickerRGB):
    """
    Color4 (rgba) picker widget for a node property.
    """
    def __init__(self, parent=...) -> None:
        ...
    
    def get_value(self): # -> tuple[Literal[0], Literal[0], Literal[0], Literal[255]]:
        ...
    


