"""
This type stub file was generated by pyright.
"""

from PySide6 import QtCore, QtGui, QtWidgets

class _NumberValueMenu(QtWidgets.QMenu):
    mouseMove = ...
    mouseRelease = ...
    stepChange = ...
    def __init__(self, parent=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def mousePressEvent(self, event): # -> None:
        """
        Disabling the mouse press event.
        """
        ...

    def mouseReleaseEvent(self, event): # -> None:
        """
        Additional functionality to emit signal.
        """
        ...

    def mouseMoveEvent(self, event): # -> None:
        """
        Additional functionality to emit step changed signal.
        """
        ...

    def set_steps(self, steps): # -> None:
        ...

    def set_data_type(self, data_type): # -> None:
        ...



class _NumberValueEdit(QtWidgets.QLineEdit):
    value_changed = ...
    def __init__(self, parent=..., data_type=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def event(self, event: QtCore.QEvent): # -> bool:
        ...

    def mouseMoveEvent(self, event: QtGui.QMouseEvent): # -> None:
        ...

    def mousePressEvent(self, event: QtGui.QMouseEvent): # -> None:
        ...

    def mouseReleaseEvent(self, event: QtGui.QMouseEvent): # -> None:
        ...

    def keyPressEvent(self, event: QtGui.QKeyEvent): # -> None:
        ...

    def set_data_type(self, data_type): # -> None:
        ...

    def set_steps(self, steps=...): # -> None:
        ...

    def get_value(self): # -> int | float:
        ...

    def set_value(self, value): # -> None:
        ...



class IntValueEdit(_NumberValueEdit):
    def __init__(self, parent=...) -> None:
        ...



class FloatValueEdit(_NumberValueEdit):
    def __init__(self, parent=...) -> None:
        ...



if __name__ == '__main__':
    app = ...
    int_edit = ...
    float_edit = ...
    widget = ...
    layout = ...
