"""
This type stub file was generated by pyright.
"""

from QtGraphology.custom_widgets.properties_bin.prop_widgets_abstract import BaseProperty

class NodePropertyWidgetFactory:
    """
    Node property widget factory for mapping the corresponding property widget
    to the Properties bin.
    """
    def __init__(self) -> None:
        ...

    def get_widget(self, widget_type=...) -> BaseProperty:
        """
        Return a new instance of a node property widget.

        Args:
            widget_type (int): widget type index.

        Returns:
            BaseProperty: node property widget.
        """
        ...
