"""
This type stub file was generated by pyright.
"""

from QtGraphology.custom_widgets import CustomCheckBox
from PySide6 import QtWidgets

class PropLabel(QtWidgets.QLabel):
    """
    Displays a node property as a "QLabel" widget in the PropertiesBin widget.
    """
    value_changed = ...
    def __repr__(self): # -> str:
        ...

    def get_value(self): # -> str:
        ...

    def set_value(self, value): # -> None:
        ...



class PropLineEdit(QtWidgets.QLineEdit):
    """
    Displays a node property as a "QLineEdit" widget in the PropertiesBin
    widget.
    """
    value_changed = ...
    def __init__(self, parent=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def get_value(self): # -> str:
        ...

    def set_value(self, value): # -> None:
        ...



class PropTextEdit(QtWidgets.QTextEdit):
    """
    Displays a node property as a "QTextEdit" widget in the PropertiesBin
    widget.
    """
    value_changed = ...
    def __init__(self, parent=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def focusInEvent(self, event): # -> None:
        ...

    def focusOutEvent(self, event): # -> None:
        ...

    def get_value(self): # -> str:
        ...

    def set_value(self, value): # -> None:
        ...



class PropComboBox(QtWidgets.QComboBox):
    """
    Displays a node property as a "QComboBox" widget in the PropertiesBin
    widget.
    """
    value_changed = ...
    def __init__(self, parent=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def items(self): # -> list[str]:
        """
        Returns items from the combobox.

        Returns:
            list[str]: list of strings.
        """
        ...

    def set_items(self, items): # -> None:
        """
        Set items on the combobox.

        Args:
            items (list[str]): list of strings.
        """
        ...

    def get_value(self): # -> str:
        ...

    def set_value(self, value): # -> None:
        ...



class PropCheckBox(CustomCheckBox):
    """
    Displays a node property as a "QCheckBox" widget in the PropertiesBin
    widget.
    """
    value_changed = ...
    def __init__(self, parent=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def get_value(self): # -> bool:
        ...

    def set_value(self, value): # -> None:
        ...



class PropSpinBox(QtWidgets.QSpinBox):
    """
    Displays a node property as a "QSpinBox" widget in the PropertiesBin widget.
    """
    value_changed = ...
    def __init__(self, parent=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def get_value(self): # -> int:
        ...

    def set_value(self, value): # -> None:
        ...



class PropDoubleSpinBox(QtWidgets.QDoubleSpinBox):
    """
    Displays a node property as a "QDoubleSpinBox" widget in the PropertiesBin
    widget.
    """
    value_changed = ...
    def __init__(self, parent=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def get_value(self): # -> float:
        ...

    def set_value(self, value): # -> None:
        ...
