"""
This type stub file was generated by pyright.
"""

from PySide6 import QtWidgets

class BaseMenu(QtWidgets.QMenu):
    def __init__(self, *args, **kwargs) -> None:
        ...

    def get_menu(self, name, node_id=...): # -> QObject | None:
        ...

    def get_menus(self, node_class): # -> list[Any]:
        ...



class GraphAction(QtWidgets.QAction):
    executed = ...
    def __init__(self, *args, **kwargs) -> None:
        ...

    def get_action(self, name): # -> None:
        ...



class NodeAction(GraphAction):
    executed = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
