"""
This type stub file was generated by pyright.
"""

_current_user_directory = ...
def set_dir(file): # -> None:
    ...

class FileDialog:
    @staticmethod
    def getSaveFileName(parent=..., title=..., file_dir=..., ext_filter=...): # -> Tuple[str, str]:
        ...
    
    @staticmethod
    def getOpenFileName(parent=..., title=..., file_dir=..., ext_filter=...): # -> Tuple[str, str]:
        ...
    


class BaseDialog:
    @staticmethod
    def message_dialog(text=..., title=...): # -> None:
        ...
    
    @staticmethod
    def question_dialog(text=..., title=...): # -> bool:
        ...
    


