"""
This type stub file was generated by pyright.
"""

from PySide6 import QtWidgets

class NodeGraphWidget(QtWidgets.QTabWidget):
    def __init__(self, parent=...) -> None:
        ...

    def add_viewer(self, viewer, name, node_id): # -> None:
        ...

    def remove_viewer(self, viewer): # -> None:
        ...



class SubGraphWidget(QtWidgets.QWidget):
    def __init__(self, parent=..., graph=...) -> None:
        ...

    @property
    def navigator(self): # -> NodeNavigationWidget:
        ...

    def add_viewer(self, viewer, name, node_id): # -> None:
        ...

    def remove_viewer(self, viewer=...): # -> None:
        ...

    def hide_viewer(self, viewer): # -> None:
        ...

    def show_viewer(self, viewer): # -> None:
        ...
