"""
This type stub file was generated by pyright.
"""

from PySide6 import QtWidgets

class TabSearchCompleter(QtWidgets.QCompleter):
    """
    QCompleter adapted from:
    https://stackoverflow.com/questions/5129211/qcompleter-custom-completion-rules
    """
    def __init__(self, nodes=..., parent=...) -> None:
        ...

    def splitPath(self, path): # -> list[Any]:
        ...

    def updateModel(self): # -> None:
        ...

    def setModel(self, model): # -> None:
        ...



class TabSearchLineEditWidget(QtWidgets.QLineEdit):
    tab_pressed = ...
    def __init__(self, parent=...) -> None:
        ...

    def keyPressEvent(self, event): # -> None:
        ...



class TabSearchMenuWidget(QtWidgets.QMenu):
    search_submitted = ...
    def __init__(self, node_dict=...) -> None:
        ...

    def __repr__(self): # -> str:
        ...

    def keyPressEvent(self, event): # -> None:
        ...

    def build_menu_tree(self): # -> None:
        ...

    def set_nodes(self, node_dict=...): # -> None:
        ...
