"""
This type stub file was generated by pyright.
"""

from PySide6 import QtWidgets

class NodeNavigationDelagate(QtWidgets.QStyledItemDelegate):
    def paint(self, painter, option, index): # -> None:
        """
        Args:
            painter (QtGui.QPainter):
            option (QtGui.QStyleOptionViewItem):
            index (QtCore.QModelIndex):
        """
        ...



class NodeNavigationWidget(QtWidgets.QListView):
    navigation_changed = ...
    def __init__(self, parent=...) -> None:
        ...

    def keyPressEvent(self, event): # -> None:
        ...

    def mouseReleaseEvent(self, event): # -> None:
        ...

    def clear(self): # -> None:
        ...

    def add_label_item(self, label, node_id): # -> None:
        ...

    def update_label_item(self, label, node_id): # -> None:
        ...

    def remove_label_item(self, node_id): # -> None:
        ...



if __name__ == '__main__':
    def on_nav_changed(selected_id, remove_ids): # -> None:
        ...

    app = ...
    widget = ...
