"""
This type stub file was generated by pyright.
"""

from QtGraphology.base.node import NodeObject

"""
This type stub file was generated by pyright.
"""
class BackdropNode(NodeObject):
    """
    The ``QtGraphology.BackdropNode`` class allows other node object to be
    nested inside, it's mainly good for grouping nodes together.

    .. inheritance-diagram:: QtGraphology.BackdropNode

    .. image:: ../_images/backdrop.png
        :width: 250px

    -
    """
    NODE_NAME = ...
    def __init__(self, qgraphics_views=...) -> None:
        ...

    def on_backdrop_updated(self, update_prop, value=...):
        """
        Slot triggered by the "on_backdrop_updated" signal from
        the node graph.

        Args:
            update_prop (str): update property type.
            value (object): update value (optional)
        """
        ...

    def auto_size(self):
        """
        Auto resize the backdrop node to fit around the intersecting nodes.
        """
        ...

    def wrap_nodes(self, nodes):
        """
        Set the backdrop size to fit around specified nodes.

        Args:
            nodes (list[QtGraphology.NodeObject]): list of nodes.
        """
        ...

    def nodes(self):
        """
        Returns nodes wrapped within the backdrop node.

        Returns:
            list[QtGraphology.BaseNode]: list of node under the backdrop.
        """
        ...

    def set_text(self, text=...):
        """
        Sets the text to be displayed in the backdrop node.

        Args:
            text (str): text string.
        """
        ...

    def text(self):
        """
        Returns the text on the backdrop node.

        Returns:
            str: text string.
        """
        ...

    def set_size(self, width, height):
        """
        Sets the backdrop size.

        Args:
            width (float): backdrop width size.
            height (float): backdrop height size.
        """
        ...

    def size(self):
        """
        Returns the current size of the node.

        Returns:
            tuple: node width, height
        """
        ...

    def inputs(self):
        ...

    def outputs(self):
        ...
