"""
This type stub file was generated by pyright.
"""

from QtGraphology.nodes.base_node import BaseNode

class PortInputNode(BaseNode):
    """
    The ``PortInputNode`` is the node that represents a input port from a
    :class:`QtGraphology.GroupNode` when expanded in a
    :class:`QtGraphology.SubGraph`.

    .. inheritance-diagram:: QtGraphology.nodes.port_node.PortInputNode
        :parts: 1

    .. image:: ../_images/port_in_node.png
        :width: 150px

    -
    """
    NODE_NAME = ...
    def __init__(self, qgraphics_item=..., parent_port=...) -> None:
        ...

    @property
    def parent_port(self): # -> None:
        """
        The parent group node port representing this node.

        Returns:
            QtGraphology.Port: port object.
        """
        ...

    def add_input(self, name=..., multi_input=..., display_name=..., color=..., locked=..., painter_func=...):
        """
        Warnings:
            This is not available for the ``PortInputNode`` class.
        """
        ...

    def add_output(self, name=..., multi_output=..., display_name=..., color=..., locked=..., painter_func=...): # -> None:
        """
        Warnings:
            This function is called by :meth:`QtGraphology.SubGraph.expand_group_node`
            and is not available for the ``PortInputNode`` class.
        """
        ...



class PortOutputNode(BaseNode):
    """
    The ``PortOutputNode`` is the node that represents a output port from a
    :class:`QtGraphology.GroupNode` when expanded in a
    :class:`QtGraphology.SubGraph`.

    .. inheritance-diagram:: QtGraphology.nodes.port_node.PortOutputNode
        :parts: 1

    .. image:: ../_images/port_out_node.png
        :width: 150px

    -
    """
    NODE_NAME = ...
    def __init__(self, qgraphics_item=..., parent_port=...) -> None:
        ...

    @property
    def parent_port(self): # -> None:
        """
        The parent group node port representing this node.

        Returns:
            QtGraphology.Port: port object.
        """
        ...

    def add_input(self, name=..., multi_input=..., display_name=..., color=..., locked=..., painter_func=...): # -> None:
        """
        Warnings:
            This function is called by :meth:`QtGraphology.SubGraph.expand_group_node`
            and is not available for the ``PortOutputNode`` class.
        """
        ...

    def add_output(self, name=..., multi_output=..., display_name=..., color=..., locked=..., painter_func=...):
        """
        Warnings:
            This is not available for the ``PortOutputNode`` class.
        """
        ...
