"""
This type stub file was generated by pyright.
"""

import importlib.util
from PySide6.QtWidgets import QCheckBox

"""
This type stub file was generated by pyright.
"""
class CustomCheckBox(QCheckBox):
    def __init__(self, *args, **kwargs) -> None:
        ...

    def comel_checkbox_fix(self, size=...):
        ...
