"""
This type stub file was generated by pyright.
"""

from PySide6 import QtWidgets

class XDisabledItem(QtWidgets.QGraphicsItem):
    """
    Node disabled overlay item.

    Args:
        parent (NodeItem): the parent node item.
        text (str): disable overlay text.
    """
    def __init__(self, parent=..., text=...) -> None:
        ...

    def boundingRect(self): # -> QRectF:
        ...

    def paint(self, painter, option, widget): # -> None:
        """
        Draws the overlay disabled X item on top of a node item.

        Args:
            painter (QtGui.QPainter): painter used for drawing the item.
            option (QtGui.QStyleOptionGraphicsItem):
                used to describe the parameters needed to draw.
            widget (QtWidgets.QWidget): not used.
        """
        ...
