"""
This type stub file was generated by pyright.
"""

from QtGraphology.qgraphics.node_base import NodeItem

class CircleNodeItem(NodeItem):
    """
    Circle Node item.

    Args:
        name (str): name displayed on the node.
        parent (QtWidgets.QGraphicsItem): parent item.
    """
    def __init__(self, name=..., parent=...) -> None:
        ...
