"""
This type stub file was generated by pyright.
"""

from PySide6 import QtWidgets

class SlicerPipeItem(QtWidgets.QGraphicsPathItem):
    """
    Base item used for drawing the pipe connection slicer.
    """
    def __init__(self) -> None:
        ...

    def paint(self, painter, option, widget): # -> None:
        """
        Draws the slicer pipe.

        Args:
            painter (QtGui.QPainter): painter used for drawing the item.
            option (QtGui.QStyleOptionGraphicsItem):
                used to describe the parameters needed to draw.
            widget (QtWidgets.QWidget): not used.
        """
        ...

    def draw_path(self, p1, p2): # -> None:
        ...
