"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class NodeMenuError(Exception):
    ...


class NodePropertyError(Exception):
    ...


class NodeWidgetError(Exception):
    ...


class NodeCreationError(Exception):
    ...


class NodeDeletionError(Exception):
    ...


class NodeRegistrationError(Exception):
    ...


class PortError(Exception):
    ...


class PortRegistrationError(Exception):
    ...


