"""
This type stub file was generated by pyright.
"""

from typing_extensions import NotRequired, TypedDict

class TSDGraph(TypedDict):
    acyclic: bool
    pipe_style: int
    pipe_slicing: bool
    pipe_collision: bool
    layout_direction: int
    accept_connection_types: dict
    reject_connection_types: dict
    ...


T_PORTS = dict[str, dict[str, list[str]]]
class TSDNode(TypedDict):
    pos: list[int]
    icon: str | None
    name: str
    color: list[int]
    type_: str
    width: float
    height: float
    custom: dict
    visible: bool
    disabled: bool
    selected: bool
    text_color: list[int]
    border_color: list[int]
    layout_direction: int
    input_ports: NotRequired[T_PORTS]
    output_ports: NotRequired[T_PORTS]
    subgraph_session: dict
    port_deletion_allowed: bool
    ...


TSDConnections = TypedDict("TSDConnections", { "in": list[str],"out": list[str] })
class TSerializedData(TypedDict):
    graph: TSDGraph
    nodes: dict[str, TSDNode]
    connections: NotRequired[list[TSDConnections]]
    ...


